### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Sixdd6** [spektor56/PegasusExportPlugin#1]
I'd like to throw this out there in case it's something you'd consider. I have a rather large Launchbox collection and have recently decided to switch to linux which sadly Launchbox does not support. Would you consider making this plugin into a standalone application?

**Comment by spektor56** [comment]
This is a plugin for Launchbox.  I originally created it as a standalone program but decided to change it to a plugin so that it will always work even if Jason decides to change the folder structure or naming convention for files.  It uses the Launchbox's own API to find the media and export it.

**Comment by Sixdd6** [comment]
I'm on linux, not windows. I was using windows but their latest update completely wrecked my windows install so I am now on linux. I was hoping that your plugin would check the xml directly but I see that is not the case, so nevermind I suppose.
