### ISSUE TITLE
Support for multi-disc games

### ISSUE THREAD

**Issue by PlayingKarrde** [spektor56/PegasusExportPlugin#3]
Pegasus (and LaunchBox) now supports multi-disc games but the exporter does not. I believe it is looking for the Other Apps property.

Here is an example of a multi-disc disc game:

game: Chrono Cross
files: 
  Chrono Cross Disc 1.cue
  Chrono Cross Disc 2.cue
developer: Square Enix
genre: Role-playing
description: Chrono Cross is a sequel to the SNES RPG  Chrono Trigger.
release: 1999-11-18
players: 1
rating: 80%

**Comment by spektor56** [comment]
Ok i added multi-disk support, but for the assets the folder is named after the file name.  Now that there are multiple files what should i do here?  Do asset files need to be added to the metadata file now?

**Comment by PlayingKarrde** [comment]
I'll do some tests (I'm not at my computer right now) but I believe just taking the first file into account will be enough.

**Comment by PlayingKarrde** [comment]
Just tested it and it's working great. Thanks for this.
